# Generated by Django 5.2.7 on 2025-10-23 03:54

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()

def migrate_posts_data(apps, schema_editor):
    Post = apps.get_model('communities', 'Post')
    Reply = apps.get_model('communities', 'Reply')
    
    # Get or create a default user for existing posts
    try:
        default_user = User.objects.first()
        if not default_user:
            default_user = User.objects.create_user(
                username='default_user',
                email='default@example.com',
                password='defaultpass123',
                first_name='Default',
                last_name='User'
            )
    except Exception:
        # If we can't create a user, skip migration
        return
    
    # Update posts to use the default user
    for post in Post.objects.all():
        if hasattr(post, 'author') and isinstance(post.author, str):
            post.author = default_user
            post.save()
    
    # Update replies to use the default user
    for reply in Reply.objects.all():
        if hasattr(reply, 'user') and isinstance(reply.user, str):
            reply.user = default_user
            reply.save()

def reverse_migrate_posts_data(apps, schema_editor):
    # This is a destructive operation, so we'll leave it empty
    # In production, you'd want to implement proper reverse migration
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_posts_data, reverse_migrate_posts_data),
    ]
